import numpy as np

TRIMS = np.array(
    [
        [0.0, 0.0, 0.0],
        [0.5, 0.0, 0.0],
        [0.0, 0.5, 0.0],
        [0.0, 0.0, 0.5],
        [0.5, 0.5, 0.0],
        [0.5, 0.0, 0.5],
        [0.0, 0.5, 0.5],
        [0.5, 0.5, 0.5],
    ]
)


def check_vector_in_array(vector, array):
    """Checks if a vector is in an array. Works with lists"""
    return np.isclose(vector, array).all(1).any()


def is_trim(kpoint):
    """Checks if kpoint is a trim. Works with vectors and arrays."""
    if kpoint.ndim == 1:
        return np.isclose(kpoint, -kpoint % 1).all()
    else:
        return np.isclose(kpoint, -kpoint % 1).all(1)


def count_trims(kpoints):
    """Counts the number of trims in a kpoint array."""
    return is_trim(kpoints).sum()


def check_kpoints(kpoints):
    """Performs checks on the kpoints to see if any are repeated."""
    seen = []
    repeated = []

    for k in kpoints:
        if len(seen) == 0:
            seen.append(k)
        elif not check_vector_in_array(k, seen):
            seen.append(k)
        else:
            if len(repeated) == 0:
                repeated.append(k)
            elif not check_vector_in_array(k, repeated):
                repeated.append(k)


    return np.array(repeated)


def is_inversion(matrix):
    """Checks if a matrix is the inversion symmetry

    Parameters
    ----------
    matrix : ndarray
        rotation matrix

    Returns
    -------
    bool
        whether the rotation is inversion
    """
    return np.isclose(matrix, -np.eye(3)).all()


def sg_has_inversion(data):
    """Checks if the spacegroup has inversion from the JSON output

    Parameters
    ----------
    data : dict
        JSON output of irrep

    Returns
    -------
    str
        key of the inversion symmetry if found, else None
    """
    symmetries = data["spacegroup"]["symmetries"]

    for num, sym in symmetries.items():
        rotation = np.array(sym["rotation matrix refUC"])
        if is_inversion(rotation):
            return int(num)
    return None


def sg_has_S4(data):
    symmetries = data["spacegroup"]["symmetries"]

    for num, sym in symmetries.items():
        if (np.isclose(sym["angle pi"], 0.5)) and (sym["inversion"]):
            return int(num)

    return None


def get_kpoint_coordinates_from_json(data, refUC=False):
    """Gets kpoint coordinates from irrep's JSON output."""
    kpoint_list = []
    for kpoint in data["characters and irreps"][0]["subspace"]["k points"]:
        if refUC:
            kpoint_list.append(kpoint["k_refUC"])
        else:
            kpoint_list.append(kpoint["k"])

    return np.array(kpoint_list)


def get_kpoint_coordinates_from_info(irreps_info, refUC=False):
    """Gets kpoint coordinates from the dict generated by get_irreps_info."""
    coordinates = np.zeros((len(irreps_info), 3))
    key = "k_refUC" if refUC else "k"
    for i, kname in enumerate(irreps_info):
        coordinates[i] = irreps_info[kname][key]

    return coordinates


def filter_irreps(irreps, precision=1e-4):
    """Filters valid irreps checking that the multiplicity is real and integer."""
    irrep_list = []
    for name, multi in irreps.items():
        multi = complex(*multi)
        if np.isclose(multi.imag, 0, atol=precision) and not np.isclose(
            multi.real, 0, atol=precision
        ):
            irrep_list.append((name, np.round(multi.real)))

    return irrep_list


def get_irreps_info(data):
    """Extracts relevant information for SI calculation from irrep's JSON.

    Parameters
    ----------
    data : dict
        JSON output from irrep
    with_character : int, optional
        symmetry index to include the character of, by default None

    Returns
    -------
    dict
        dictionary with relevant info
    """
    kpoints = data["characters and irreps"][0]["subspace"]["k points"]

    irrep_info = {}
    for kpoint in kpoints:
        kpoint_list = []
        energies = kpoint["energies_mean"]#
        dims = kpoint["dimensions"]
        coords = kpoint["k"]
        coords_refUC = kpoint["k_refUC"]
        name = kpoint["kpname"]

        if name is None:
            continue

        for i, irreps in enumerate(kpoint["irreps"]):
            valid_irreps = filter_irreps(irreps)
            if len(valid_irreps) > 0:
                kpoint_list.append((energies[i], valid_irreps, dims[i]))
        irrep_info[name] = {"k": coords, "k_refUC": coords_refUC, "irreps": kpoint_list}

    return irrep_info


def get_character_info(data, symop_index):
    kpoints = data["characters and irreps"][0]["subspace"]["k points"]
    char_info = {}
    unknown_index = 0
    for kpoint in kpoints:
        characters = kpoint["characters"]
        coords = kpoint["k"]
        coords_refUC = kpoint["k_refUC"]
        name = kpoint["kpname"]
        if name is None:
            name = f"unknown{unknown_index}"
            unknown_index += 1
        try:
            op_index = kpoint["symmetries"].index(symop_index)
        except ValueError:
            continue

        kpoint_list = np.array([
            np.round(energy_chars[op_index], 3) for energy_chars in characters
            ])

        char_info[name] = {
            "k": coords,
            "k_refUC": coords_refUC,
            "characters": kpoint_list,
        }

    return char_info


def count_irreps(irrep_info, by_point=False):
    """Produce a dictionary with the irrep counts

    Parameters
    ----------
    irrep_info : dict
        dictionary generated by get_irreps_info
    by_point : bool, optional
        separate by kpoint, by default False

    Returns
    -------
    dict
        dictionary with irrep counts.
    """
    if by_point:
        irrep_count = {}
        for kpoint, info in irrep_info.items():
            kpoint_count = {}
            for irreps in [x[1] for x in info["irreps"]]:
                for name, multi in irreps:
                    kpoint_count.setdefault(name, 0.0)
                    kpoint_count[name] += multi
            irrep_count[kpoint] = {
                "k": info["k"],
                "k_refUC": info["k_refUC"],
                "counts": kpoint_count,
            }

    else:
        irrep_count = {}
        for info in irrep_info.values():
            for irreps in [x[1] for x in info["irreps"]]:
                for name, multi in irreps:
                    irrep_count.setdefault(name, 0.0)
                    irrep_count[name] += multi

    return irrep_count


def compute_invariant(irrep_counts, irrep_names, factors, mod):
    """General reduction method to compute an invariant by counting irreps

    Parameters
    ----------
    irrep_counts : dict
        plain irrep counts (not by kpoint)
    irrep_names : list
        irrep names to count
    factors : list
        factors to multiply each irrep count
    mod : int
        final modulus operation to apply to the sum

    Returns
    -------
    float
        result of the computation
    """

    counts = np.array([irrep_counts.get(name, 0.0) for name in irrep_names])
    if factors is None:
        total = counts.sum()
    else:
        factors = np.array(factors, dtype=float)
        total = (factors * counts).sum()

    if mod is None:
        return total
    else:
        return total % mod

def compute_symmetry_indicators(json_data):
    sg_number = json_data["spacegroup"]["number"]

    kpoints = get_kpoint_coordinates_from_json(json_data, refUC=False)
    repeated = check_kpoints(kpoints)

    si_results = []

    irrep_counts = count_irreps(get_irreps_info(json_data), by_point=False)

    if len(repeated) > 0:
        print("Some k-points are repeated. Please remove duplicates to compute symmetry indicators.")
        for kpoint in kpoints:
            print("\t {: .5f} {: .5f} {:.5f}".format(*kpoint))

        return
    
    inversion_index = sg_has_inversion(json_data)
    if inversion_index is not None:
        character_info = get_character_info(json_data, inversion_index)
        trim_number = len(character_info)
        if trim_number != 8:
            print("Could not compute inversion-related SIs. Wrong number of TRIMs ({})".format(trim_number))
        else:
            # z2w_j triplet
            triplet_names = [f"z2w_{j}" for j in range(1,4)]
            for z2_name, z2_value in zip(triplet_names, z2w_triplet(character_info)):
                si_results.append((z2_name, z2_value))
            # z4 
            z4_value = z4(character_info)
            si_results.append(("z4", z4_value))
            # z12 indices need z4 value
            if sg_number in [175, 191, 192]:
                z12_value = z12(irrep_counts, z4_value)
                si_results.append(("z12", z12_value))
            elif sg_number in [176, 193, 194]:
                z12_value = z12prime(irrep_counts, z4_value)
                si_results.append(("z12'", z12_value))

    s4_index = sg_has_S4(json_data)
    if s4_index is not None:
        character_info = get_character_info(json_data, s4_index)
        s4_kpoints = len(character_info)
        if s4_kpoints != 4:
            print("Could not compute z2 index. Missing {} S4-symmetric k-points".format(4-s4_kpoints))
        else:
            si_results.append(("z2", z2(character_info)))

    # SG-specific indicators
    si_list = SI_FROM_SG.get(sg_number, [])
    for si_name, si_function in si_list:
        try:
            si_results.append((si_name, si_function(irrep_counts)))
        except Exception as err:
            print("There was a problem computing the symmetry indicator", si_name)
            print(err)

    return si_results

#### SI DEFINITIONS ####

def z2w_j(character_info, j=1):
    i = j - 1
    total_inv = 0.0
    for kpoint in character_info.values():
        if is_trim(np.array(kpoint["k"])) and np.isclose(kpoint["k"][i], 0.5):
            total_inv += (kpoint["characters"] < 0.0).sum()

    return total_inv % 2


def z2w_triplet(character_info):
    return [z2w_j(character_info, j) for j in range(1, 4)]


def z4(character_info):
    total_inv = 0.0j
    for kpoint in character_info.values():
        total_inv += -kpoint["characters"].sum()

    if not np.isclose(np.imag(total_inv), 0):
        raise ValueError(
            "z4 index computation resulted in imaginary index. Check inversion traces."
        )

    total_inv = np.real(total_inv)

    return (0.5 * total_inv) % 4


def z2(character_info):
    total = 0.0j
    for kpoint in character_info.values():
        total += -kpoint["characters"].sum()

    if not np.isclose(np.imag(total), 0):
        raise ValueError(
            "z4 index computation resulted in imaginary index. Check inversion traces."
        )

    total = np.real(total) / np.sqrt(2)

    return np.round(total % 2, 3)


def z4mpi_83(irrep_counts):
    # "-Z5-Z7", "-Z6-Z8", "-Z11-Z9", "-Z10-Z12", "-A5-A7", "-A6-A8", \
    # "-A11-A9", "-A10-A12", "-R3-R4", "-R5-R6"
    irrep_names = [
        "-Z5",
        "-Z6",
        "-Z11",
        "-Z10",
        "-A5",
        "-A6",
        "-A11",
        "-A10",
        "-R3",
        "-R5",
    ]
    factors = [1.5, -0.5, -1.5, 0.5, 1.5, -0.5, -1.5, 0.5, 1.0, -1.0]
    mod = 4

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z4mpi_221(irrep_counts):
    # "-X7", "-X9", "-X6", "-X8", "-R7", "-R9", "-R10", "-R11", "-R6",
    # "-R8", "-M7", "-M6", "-M9", "-M8"

    irrep_names = [
        "-X7",
        "-X9",
        "-X6",
        "-X8",
        "-R7",
        "-R9",
        "-R10",
        "-R11",
        "-R6",
        "-R8",
        "-M7",
        "-M6",
        "-M9",
        "-M8",
    ]
    factors = [
        1.5,
        -1.5,
        -0.5,
        0.5,
        1.5,
        -1.5,
        1.0,
        -1.0,
        -0.5,
        0.5,
        1.0,
        1.0,
        -1.0,
        -1.0,
    ]
    mod = 4

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z3m0(irrep_counts):
    # "-K12", "-K8", "-K10", "-K9", "-K7", "-K11", "-GM12-GM9", "-GM10-GM11"
    irrep_names = ["-K12", "-K8", "-K10", "-K9", "-K7", "-K11", "-GM12", "-GM10"]
    factors = [-0.5, 1.5, 0.5, -0.5, 1.5, 0.5, 1.0, -1.0]
    mod = 3

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z3mpi(irrep_counts):
    # "-H12", "-H8", "-H10", "-H9", "-H7", "-H11", "-A12-A9", "-A10-A11"
    irrep_names = (["-H12", "-H8", "-H10", "-H9", "-H7", "-H11", "-A12", "-A10"],)
    factors = ([-0.5, 1.5, 0.5, -0.5, 1.5, 0.5, 1.0, -1.0],)
    mod = 3

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z6m0_175(irrep_counts):
    # "-GM7#-GM8", "-GM12#-GM9", "-GM10#-GM11", "-GM13#-GM14", \
    # "-GM15#-GM18", "-GM16#-GM17", "-K7#-K8", "-K12#-K9", "-K10#-K11", \
    # "-M3#-M4", "-M5#-M6"
    irrep_names = [
        "-GM7",
        "-GM12",
        "-GM10",
        "-GM13",
        "-GM15",
        "-GM16",
        "-K7",
        "-K12",
        "-K10#-K11",
        "-M3",
        "-M5",
    ]
    factors = [1.5, -2.5, -0.5, -1.5, 2.5, 0.5, 3.0, -5.0, -1.0, 1.5, -1.5]
    mod = 6

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z6mpi_175(irrep_counts):
    # "-A7#-A8", "-A12#-A9", "-A10#-A11", "-A13#-A14", "-A15#-A18",
    # "-A16#-A17", "-H7#-H8", "-H12#-H9", "-H10#-H11", "-L3#-L4", "-L5#-L6"
    irrep_names = [
        "-A7",
        "-A12",
        "-A10",
        "-A13",
        "-A15",
        "-A16",
        "-H7",
        "-H12",
        "-H10",
        "-L3",
        "-L5",
    ]
    factors = [1.5, -2.5, -0.5, -1.5, 2.5, 0.5, 3.0, -5.0, -1.0, 1.5, -1.5]
    mod = 6

    return compute_invariant(irrep_counts, irrep_names, factors, mod)

def z6m0_176(irrep_counts):
    return z6m0_175(irrep_counts)

def z8_83(irrep_counts):
    # 1/2+ (-): "-GM6-GM8", "-M6-M8", "-Z6-Z8", "-A6-A8", "-X3-X4", "-R3-R4"
    # 1/2- (+): "-GM10-GM12", "-M10-M12", "-Z10-Z12", "-A10-A12", "-X5-X6", "-R5-R6"
    # 3/2+ (+):"-GM5-GM7", "-M5-M7", "-Z5-Z7", "-A5-A7", "-X3-X4", "-R3-R4"
    # 3/2- (-):"-GM11-GM9", "-M11-M9", "-Z11-Z9", "-A11-A9", "-X5-X6", "-R5-R6"
    irrep_names = [
        "-GM6",
        "-M6",
        "-Z6",
        "-A6",
        "-X3",
        "-R3",
        "-GM10",
        "-M10",
        "-Z10",
        "-A10",
        "-X5",
        "-R5",
        "-GM5",
        "-M5",
        "-Z5",
        "-A5",
        "-X3",
        "-R3",
        "-GM11",
        "-M11",
        "-Z11",
        "-A11",
        "-X5",
        "-R5",
    ]
    factors = [
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
    ]
    mod = 8

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z8_87(irrep_counts):
    # 1/2+ (-): "-GM6-GM8", "-M6-M8", "-X3-X4", "-N3-N3", "-P6-P8"
    # 1/2- (+): "-GM10-GM12", "-M10-M12", "-X5-X6", "-N2-N2", "-P5-P7"
    # 3/2+ (+): "-GM5-GM7", "-M5-M7", "-X3-X4", "-N3-N3", "-P5-P7"
    # 3/2- (-): "-GM11-GM9", "-M11-M9", "-X5-X6", "-N2-N2", "-P6-P8"
    irrep_names = [
        "-GM6",
        "-M6",
        "-X3",
        "-N3",
        "-P6",
        "-GM10",
        "-M10",
        "-X5",
        "-N2",
        "-P5",
        "-GM5",
        "-M5",
        "-X3",
        "-N3",
        "-P5",
        "-GM11",
        "-M11",
        "-X5",
        "-N2",
        "-P6",
    ]
    factors = (
        [
            -0.5,
            -0.5,
            -0.5,
            -0.5,
            -0.5,
            0.5,
            0.5,
            0.5,
            0.5,
            0.5,
            1.5,
            1.5,
            1.5,
            1.5,
            1.5,
            -1.5,
            -1.5,
            -1.5,
            -1.5,
            -1.5,
        ],
    )
    mod = 8

    compute_invariant(irrep_counts, irrep_names, factors, mod)


def z8_221(irrep_counts):
    # 1/2+ (-): "-GM6", "-GM10", "-R6", "-R10", "-M7", "-M6", "-X6", "-X7"
    # 1/2- (+): "-GM8", "-GM11", "-R8", "-R11", "-M9", "-M8", "-X8", "-X9"
    # 3/2+ (+): "-GM10", "-GM7", "-R10", "-R7", "-M6", "-M7", "-X7", "-X6"
    # 3/2- (-): "-GM11", "-GM9", "-R11", "-R9", "-M8", "-M9", "-X9", "-X8"
    irrep_names = [
        "-GM6",
        "-GM10",
        "-R6",
        "-R10",
        "-M7",
        "-M6",
        "-X6",
        "-X7",
        "-GM8",
        "-GM11",
        "-R8",
        "-R11",
        "-M9",
        "-M8",
        "-X8",
        "-X9",
        "-GM10",
        "-GM7",
        "-R10",
        "-R7",
        "-M6",
        "-M7",
        "-X7",
        "-X6",
        "-GM11",
        "-GM9",
        "-R11",
        "-R9",
        "-M8",
        "-M9",
        "-X9",
        "-X8",
    ]
    factors = [
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
    ]
    mod = 8

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z8_225(irrep_counts):
    # 1/2+ (-): "-GM6", "-GM10", "-X6", "-X7", "-L8", "-L4-L5", "-W7"
    # 1/2- (+): "-GM8", "-GM11", "-X8", "-X9", "-L9", "-L6-L7", "-W6"
    # 3/2+ (+): "-GM10", "-GM7", "-X7", "-X6", "-L8", "-L4-L5", "-W6"
    # 3/2- (-): "-GM11", "-GM9", "-X9", "-X8", "-L9", "-L6-L7", "-W7"
    irrep_names = [
        "-GM6",
        "-GM10",
        "-X6",
        "-X7",
        "-L8",
        "-L4",
        "-W7",
        "-GM8",
        "-GM11",
        "-X8",
        "-X9",
        "-L9",
        "-L6",
        "-W6",
        "-GM10",
        "-GM7",
        "-X7",
        "-X6",
        "-L8",
        "-L4",
        "-W6",
        "-GM11",
        "-GM9",
        "-X9",
        "-X8",
        "-L9",
        "-L6",
        "-W7",
    ]
    factors = [
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
    ]
    mod = 8

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z8_226(irrep_counts):
    # 1/2+ (-): "-GM6", "-GM10", "-X7", "-X8", "-X9"
    # 1/2- (+): "-GM8", "-GM11", "-X9", "-X6", "-X7"
    # 3/2+ (+): "-GM10", "-GM7", "-X6", "-X8", "-X9"
    # 3/2- (-): "-GM11", "-GM9", "-X8", "-X6", "-X7"
    irrep_names = [
        "-GM6",
        "-GM10",
        "-X7",
        "-X8",
        "-X9",
        "-GM8",
        "-GM11",
        "-X9",
        "-X6",
        "-X7",
        "-GM10",
        "-GM7",
        "-X6",
        "-X8",
        "-X9",
        "-GM11",
        "-GM9",
        "-X8",
        "-X6",
        "-X7",
    ]
    factors = [
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
    ]
    mod = 8

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z8_229(irrep_counts):
    # 1/2+ (-): "-GM6", "-GM10", "-H6", "-H10", "-N5", "-P6", "-P8"
    # 1/2- (+): "-GM8", "-GM11", "-H8", "-H11", "-N6", "-P8", "-P7"
    # 3/2+ (+): "-GM10", "-GM7", "-H10", "-H7", "-N5", "-P8", "-P7"
    # 3/2- (-): "-GM11", "-GM9", "-H11", "-H9", "-N6", "-P6", "-P8"
    irrep_names = [
        "-GM6",
        "-GM10",
        "-H6",
        "-H10",
        "-N5",
        "-P6",
        "-P8",
        "-GM8",
        "-GM11",
        "-H8",
        "-H11",
        "-N6",
        "-P8",
        "-P7",
        "-GM10",
        "-GM7",
        "-H10",
        "-H7",
        "-N5",
        "-P8",
        "-P7",
        "-GM11",
        "-GM9",
        "-H11",
        "-H9",
        "-N6",
        "-P6",
        "-P8",
    ]
    factors = [
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        -0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
        -1.5,
    ]
    mod = 8

    return compute_invariant(irrep_counts, irrep_names, factors, mod)


def z12(irrep_counts, z4_value):
    z6m = (z6m0_175(irrep_counts) + z6mpi_175(irrep_counts)) % 6
    return (z6m + 3 * ((z6m - z4_value) % 4)) % 12


def z12prime(irrep_counts, z4_value):
    z6m = z6m0_176(irrep_counts)
    return (z6m + 3 * ((z6m - z4_value) % 4)) % 12

#### SG TO SI MAPPING ####


SI_FROM_SG = {
    83: [
        ("z4m_pi", z4mpi_83),
        ("z8", z8_83)
    ],
    87: [
        ("z8", z8_87)
    ],
    123: [
        ("z4m_pi", z4mpi_83),
        ("z8", z8_83)
    ],
    124: [
        ("z8", z8_83)
    ],
    127: [
        ("z4m_pi", z4mpi_83),
        ("z8", z8_83)
    ],
    128: [
        ("z8", z8_83)
    ],
    139: [
        ("z8", z8_87)
    ],
    140: [
        ("z8", z8_87)
    ],
    174: [
        ("z3m_0", z3m0),
        ("z3m_pi", z3mpi)
    ],
    175: [
        ("z6m_0", z6m0_175),
        ("z6m_pi", z6mpi_175),
        #("z12", z12) manual
    ],
    176: [
        ("z6m_0", z6m0_176),
        #("z12'", z12prime) manual
    ],
    187: [
        ("z3m_0", z3m0),
        ("z3m_pi", z3mpi)
    ],
    188: [
        ("z3m0", z3m0)
    ],
    189: [
        ("z3m_0", z3m0),
        ("z3m_pi", z3mpi)
    ],
    190: [
        ("z3m_0", z3m0)
    ],
    191: [
        ("z6m_0", z6m0_175),
        ("z6m_pi", z6mpi_175),
        #("z12", z12) manual
    ],
    192: [
        ("z6m0", z6m0_175),
        ("Z6m_pi", z6mpi_175),
        #("z12", z12) manual
    ],
    193: [
        ("z6m_0", z6m0_176),
        #("z12'", z12prime) manual
    ],
    194: [
        ("z6m_0", z6m0_176),
        #("z12'", z12prime) manual
    ],
    221: [
        ("z4m_pi", z4mpi_221),
        ("z8", z8_221)
    ],
    225: [
        ("z8", z8_225)
    ],
    226: [
        ("z8", z8_226)
    ],
    229: [
        ("z8", z8_229)
    ]
}